version: '3'
services:
  server:
    build: .
    tty: true
    volumes:
      - ./server:/app
    ports: 
      - "8081:8081"
    command: sh -c "yarn && yarn server"
  front:
    build: .
    tty: true
    volumes:
      - ./front:/app
    ports:
      - "8080:8080"
    command: sh -c "yarn && yarn dev"
