version: '3'
services:
  server:
    build: .
    tty: true
    ports: 
      - "8081:8081"
    command: "yarn server"
  front:
    build: .
    tty: true
    ports:
      - "8080:8080"
    command: "yarn dev"
